# Generated by Django 4.2.18 on 2026-07-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Informe a matrícula do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do Aluno', max_length=70)),
                ('data_inicial', models.DateField(help_text='Informe a data de inicial de matrícula do Aluno')),
                ('data_final', models.DateField(blank=True, help_text='Informe a data de final de matrícula do Aluno', null=True)),
            ],
        ),
    ]
